//+--------------------------------------------------------------------------
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved
// AGPLv3 2017 Martino Dell'Ambrogio
//
// File:        adcsexitplus.idl
//
// Contents:    IDL source for adcsexitplus
//
//---------------------------------------------------------------------------

import "wtypes.idl";
import "certexit.idl";
import "certmod.idl";


//+--------------------------------------------------------------------------
// certexit Type library
//+--------------------------------------------------------------------------

[
    uuid(d29571d0-c2c8-11d2-b313-00c04f79dc72),
    version(1.0),
    helpstring("CertExitPlus 1.0 Type Library")
]

library CERTEXITPLUSLib
{
    importlib("stdole2.tlb");

    [
	uuid(d2075560-c2c8-11d2-b313-00c04f79dc72),
	helpstring("CertExitPlus Class")
    ]
    coclass CCertExitPlus
    {
	[default] interface ICertExit;
    };

    [
	uuid(d3099410-c2c8-11d2-b313-00c04f79dc72),
	helpstring("CertManageExitModulePlus Class")
    ]
    coclass CCertManageExitModulePlus
    {
	[default] interface ICertManageModule;
    };
};
